# Generated by Django 6.0.7 on 2026-07-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_years',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('principal', 'Principal'), ('hod', 'HOD'), ('lecturer', 'Lecturer'), ('student', 'Student')], max_length=20),
        ),
    ]
