# Generated by Django 6.0.7 on 2026-07-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_department_user_assigned_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('principal', 'Principal'), ('hod', 'HOD'), ('lecturer', 'Lecturer'), ('student', 'Student'), ('staff', 'Non‑Teaching Staff')], max_length=20),
        ),
    ]
