# Generated by Django 6.0.7 on 2026-07-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('principal', 'Principal'), ('hod', 'HOD'), ('lecturer', 'Lecturer'), ('student', 'Student'), ('staff', 'Non‑Teaching Staff'), ('admin', 'Admin')], max_length=20),
        ),
    ]
