# Generated by Django 6.0.7 on 2026-07-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
