# Generated by Django 6.0.7 on 2026-07-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_holidaysetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaysetting',
            name='is_holiday',
        ),
        migrations.RemoveField(
            model_name='holidaysetting',
            name='reason',
        ),
        migrations.AddField(
            model_name='holidaysetting',
            name='status',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('working', 'Working Day')], default='work', max_length=10),
            preserve_default=False,
        ),
    ]
