# Generated by Django 6.0.7 on 2026-08-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile'),
        ('attendance', '0005_remove_holidaysetting_is_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='section',
            field=models.ForeignKey(blank=True, help_text="Leave blank for 'All Sections'", null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.section'),
        ),
    ]
