# Generated by Django 5.0.14 on 2026-09-02 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_academicyear_studentenrollment_language1_and_more'),
        ('attendance', '0006_allow_null_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.academicyear'),
        ),
    ]
